---
- name: Dependence hosts
  hosts: k8s_cluster
  vars:
    # ansible_python_interpreter: /usr/bin/python
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: ../roles/dependence-hosts }
